version: '3.8'

services:
  app:
    image: app
    container_name: app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=app
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres

  db:
    image: postgres:latest
    container_name: postgres-container
    networks:
      - app-network
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    networks:
      - app-network
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app-network:
    driver: bridge
